-- CreateTable
CREATE TABLE "NEW_SOURCE" (
    "id" INTEGER NOT NULL,
    "source_name" TEXT NOT NULL,
    "year_version" TEXT,

    CONSTRAINT "NEW_SOURCE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NEW_JOURNAL" (
    "id" SERIAL NOT NULL,
    "journal_title" TEXT NOT NULL,
    "publisher" TEXT,
    "active_status" TEXT DEFAULT 'Active',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NEW_JOURNAL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NEW_JOURNAL_ISSN" (
    "id" SERIAL NOT NULL,
    "journal_id" INTEGER NOT NULL,
    "issn" TEXT NOT NULL,
    "issn_type" TEXT,

    CONSTRAINT "NEW_JOURNAL_ISSN_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NEW_SUBJECT_AREA" (
    "id" SERIAL NOT NULL,
    "source_id" INTEGER NOT NULL,
    "area_code" TEXT,
    "area_name" TEXT NOT NULL,
    "area_group" TEXT,
    "major_group" TEXT,

    CONSTRAINT "NEW_SUBJECT_AREA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NEW_JOURNAL_AREA_MAPPING" (
    "journal_id" INTEGER NOT NULL,
    "subject_area_id" INTEGER NOT NULL,

    CONSTRAINT "NEW_JOURNAL_AREA_MAPPING_pkey" PRIMARY KEY ("journal_id","subject_area_id")
);

-- CreateTable
CREATE TABLE "NEW_JOURNAL_RANKING" (
    "id" SERIAL NOT NULL,
    "journal_id" INTEGER NOT NULL,
    "source_id" INTEGER NOT NULL,
    "rank_value" TEXT NOT NULL,

    CONSTRAINT "NEW_JOURNAL_RANKING_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "NEW_JOURNAL_ISSN_journal_id_issn_key" ON "NEW_JOURNAL_ISSN"("journal_id", "issn");

-- CreateIndex
CREATE UNIQUE INDEX "NEW_SUBJECT_AREA_source_id_area_name_key" ON "NEW_SUBJECT_AREA"("source_id", "area_name");

-- AddForeignKey
ALTER TABLE "NEW_JOURNAL_ISSN" ADD CONSTRAINT "NEW_JOURNAL_ISSN_journal_id_fkey" FOREIGN KEY ("journal_id") REFERENCES "NEW_JOURNAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NEW_SUBJECT_AREA" ADD CONSTRAINT "NEW_SUBJECT_AREA_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "NEW_SOURCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NEW_JOURNAL_AREA_MAPPING" ADD CONSTRAINT "NEW_JOURNAL_AREA_MAPPING_journal_id_fkey" FOREIGN KEY ("journal_id") REFERENCES "NEW_JOURNAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NEW_JOURNAL_AREA_MAPPING" ADD CONSTRAINT "NEW_JOURNAL_AREA_MAPPING_subject_area_id_fkey" FOREIGN KEY ("subject_area_id") REFERENCES "NEW_SUBJECT_AREA"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NEW_JOURNAL_RANKING" ADD CONSTRAINT "NEW_JOURNAL_RANKING_journal_id_fkey" FOREIGN KEY ("journal_id") REFERENCES "NEW_JOURNAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NEW_JOURNAL_RANKING" ADD CONSTRAINT "NEW_JOURNAL_RANKING_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "NEW_SOURCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;
